In [62]:
"""Industrials List

This file calculates the top 5 stocks in the the industrials list by marketcap

"""
# Import modules
import csv
from pathlib import Path
import pandas as pd
import numpy as np

In [63]:
# Read CSV file 
sp500_w_marketcap = pd.read_csv(
    Path("../Resources/stock_industry_marketcap.csv")
)
sp500_w_marketcap

    Symbol             GICS Sector    Market_Cap
0      MMM             Industrials  1.144546e+11
1      ABT             Health Care  2.166563e+11
2     ABBV             Health Care  2.034378e+11
3     ABMD             Health Care  1.581906e+10
4      ACN  Information Technology  2.031204e+11
..     ...                     ...           ...
498    YUM  Consumer Discretionary  3.981149e+10
499   ZBRA  Information Technology  3.045970e+10
500    ZBH             Health Care  3.130774e+10
501   ZION              Financials  8.701906e+09
502    ZTS             Health Care  9.677650e+10

[503 rows x 3 columns]

In [64]:
# set index to GICS Sector
sp500_w_marketcap = sp500_w_marketcap.set_index("GICS Sector")
sp500_w_marketcap

                       Symbol    Market_Cap
GICS Sector
Industrials               MMM  1.144546e+11
Health Care               ABT  2.166563e+11
Health Care              ABBV  2.034378e+11
Health Care              ABMD  1.581906e+10
Information Technology    ACN  2.031204e+11
...                       ...           ...
Consumer Discretionary    YUM  3.981149e+10
Information Technology   ZBRA  3.045970e+10
Health Care               ZBH  3.130774e+10
Financials               ZION  8.701906e+09
Health Care               ZTS  9.677650e+10

[503 rows x 2 columns]

In [65]:
# filter out industrials
industrials = sp500_w_marketcap.loc["Industrials"]
industrials

            Symbol    Market_Cap
GICS Sector
Industrials    MMM  1.144546e+11
Industrials    ALK  7.208412e+09
Industrials   ALLE  1.231529e+10
Industrials    AAL  1.353835e+10
Industrials    AME  3.165210e+10
...            ...           ...
Industrials    URI  2.355111e+10
Industrials   VRSK  3.078270e+10
Industrials    WAB  1.627273e+10
Industrials     WM  6.261410e+10
Industrials    XYL  2.295895e+10

[74 rows x 2 columns]

In [70]:
# industrials_list = industrials.set_index("Market_Cap").sort_values(by="Market_Cap").iloc[0:5]
industrials_top_5 = industrials.set_index("Market_Cap").sort_values(by="Market_Cap", ascending=False).iloc[0:5]
industrials_top_5

             Symbol
Market_Cap
9.043755e+11     GE
1.668881e+11    UPS
1.596645e+11    HON
1.455886e+11    UNP
1.344712e+11     BA

In [72]:
industrials_list = industrials_top_5.values.tolist()
industrials_list

[['GE'], ['UPS'], ['HON'], ['UNP'], ['BA']]

In [76]:
sp500_w_marketcap = pd.read_csv(Path("../Resources/stock_industry_marketcap.csv"))
sp500_w_marketcap = sp500_w_marketcap.set_index("GICS Sector")
industrials = sp500_w_marketcap.loc["Industrials"]
industrials_top_5 = industrials.set_index("Market_Cap").sort_values(by="Market_Cap", ascending=False).iloc[0:5]
industrials_list = industrials_top_5.values.tolist()
industrials_list

[['GE'], ['UPS'], ['HON'], ['UNP'], ['BA']]

In [ ]:
for sector in sp500_w_marketcap: